### ISSUE TITLE
[CMS] Import CSV file with details about location of buildings

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/seismic-risc#11]
As an admin user of the platform I want to be able to import a CSV file with the location of buildings, state, seismic risk and other additional information.

The file is the one attached to this issue:.
[LISTA imobile PMB completa_2018.xlsx](https://github.com/code4romania/seismic-alert/files/3436455/LISTA.imobile.PMB.completa_2018.xlsx)

For the look and feel of the UI check out https://www.figma.com/file/qOyFrU8T6LXnJw7YcoVW85/Seismic-Risk?node-id=0%3A1

**Comment by RaduCStefanescu** [comment]
In progress @grinchfedorov

**Comment by tudoramariei** [comment]
PR #22 fixes this issue, it should be closed now
