### ISSUE TITLE
[Map] Display a map containing seismic risk information 

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/seismic-risc#12]
The information about buildings that is saved in the database should be displayed on a map, using pins to highlight the seismic risk of the building. The pins colour changes according to the severity.

The map provider should be OpenStreetMaps.

For the look and feel of the UI check out https://www.figma.com/file/qOyFrU8T6LXnJw7YcoVW85/Seismic-Risk?node-id=0%3A1

**Comment by cnstlungu** [comment]
Taking this one

**Comment by RaduCStefanescu** [comment]
In progress @cnstlungu
