### ISSUE TITLE
[Map] Navigate to a single map entry and display information

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/seismic-risc#13]
As an user of the platform, I want to be able to drill down to a single location on the map and see complete information about that location.

For the look and feel of the UI check out https://www.figma.com/file/qOyFrU8T6LXnJw7YcoVW85/Seismic-Risk?node-id=0%3A1

**Comment by cnstlungu** [comment]
@RaduCStefanescu please mark this one in progress as well. GH-21 already allows to select a single location on the map and display information about it.
Looking towards improving the look and feel, but the functionality is already there.

![image](https://user-images.githubusercontent.com/10930578/65542240-77489c80-df17-11e9-9614-03e32df8f493.png)
Regards

**Comment by cnstlungu** [comment]
@RaduCStefanescu  btw, maybe instead displaying all the information about a building in the popup we could show just a subset of the columns and link to the building's profile that holds full data about the building?
A building profile could also be useful to aggregate input/updates/photos from dwellers/prospective buyers/other interested parties.
