### ISSUE TITLE
[Map] Search locations on map based on address

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/seismic-risc#15]
As a user of the platform, I want to be able to search location on the map based on the address.

Update: The search bar is implemented in the client but there is no connection to the backend. Functionality should be implemented in Django, on the backend.

**Comment by cnstlungu** [comment]
taking this one

**Comment by RaduCStefanescu** [comment]
Frontend search bar implemented, but no information is sent to backend. 
The functionality still needs to be implemented in backend.

**Comment by cnstlungu** [comment]
@RaduCStefanescu  unfortunately I didn't get to this one, so this is up for grabs. Regards

**Comment by tudoramariei** [comment]
Thanks for letting us know, @cnstlungu! 😄

**Comment by francisc-czobor** [comment]
I'll do it. @RaduCStefanescu @tudoramariei assign it to me

**Comment by RaduCStefanescu** [comment]
All yours @francisc-czobor
