### ISSUE TITLE
[DevOps] Set-up automatic Here! Maps API key configuration

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#151]
Currently, the API key is supposed to be manually set in [client/src/components/HereMap.js](http://github.com/code4romania/seismic-risc/tree/master/client/src/components/HereMap.js#L8) but the best proper is to set it in the `.env` file set at initialization. For reference, see how `NODE_ENV` is being used there.

The configuration is read at build time, and we should have at least 3 configurations available:
- `local` - for local development
- `development` - for the development environment
- `production` - for the live deployment

**Comment by crisp2u** [comment]
I think we need to setup 3 separate keys for each environment and protect the keys by restricting the domain they can be used. I'll have a look on how we can make this easy on local development.
