### ISSUE TITLE
[admin] Properly arrange categories in the admin page

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#153]
Currently, some admin actions are not placed in the right category
The changes that should be done are:

- [ ] _SITES_ should be removed entirely
- [ ] _TAGGIT_ should be removed entirely and _Tags_ should be placed under _BLOG_
- [ ] _Categories_ should be moved from _PAGES_ to _BLOG_ since the blog posts should be under different categories while website pages won't be too many to need categories

_Arrow demonstration_ of the changes:
![Screenshot 2020-02-27 at 17 58 04](https://user-images.githubusercontent.com/2820084/75461140-ff314780-598a-11ea-9d17-192773400b99.png)

**Comment by emanuelbesliu** [comment]
I'll do it

**Comment by tudoramariei** [comment]
Moved _in progress_, @emanuelbesliu 
Thanks for taking it!

**Comment by emanuelbesliu** [comment]
Pull request #171

**Comment by tudoramariei** [comment]
When creating this issue, I was not fully aware of the complexity of customizing the Django Admin interface. Since this introduces dependencies that are not maintained or that have a high risk of being abandoned by their maintainers, I would rather we dropped this.
I am sorry for not making use of the work that was put in already.
