### ISSUE TITLE
[Map] Add form for inserting new information about building

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/seismic-risc#16]
As a visitor of the platform, I want to be able to have a form where I can fill in details about new buildings, that are not in the platform.

For the look and feel of the UI check out https://www.figma.com/file/qOyFrU8T6LXnJw7YcoVW85/Seismic-Risk?node-id=0%3A1

**Comment by costibleotu** [comment]
Done

**Comment by costibleotu** [comment]
Done
