### ISSUE TITLE
[Frontend] Change HereMap from static image to interactive map

### ISSUE THREAD

**Issue by vladplesu** [code4romania/seismic-risc#166]
Current behavior:

Map component renders a static image with markers on indicated points. Unable to zoom or click on map markers.

Expected behavior:

User should be able to zoom, move around the map and click on map markers to see the building details.

**Comment by tudoramariei** [comment]
As discussed with @vladplesu, assigning this to him

**Comment by tudoramariei** [comment]
Closed by #183
