### ISSUE TITLE
[CMS] Admin can approve/reject new information inserted by visitors

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/seismic-risc#17]
As an admin of the platform I want to be able to approve or reject the information that is inserted by visitors in the platform.
When a new entry is accepted, we need to retrieve the geo location based on the address and display the new information on the map.

For the look and feel of the UI check out https://www.figma.com/file/qOyFrU8T6LXnJw7YcoVW85/Seismic-Risk?node-id=0%3A1

**Comment by costibleotu** [comment]
Done
