### ISSUE TITLE
[Docs] Add instructions in the main README for setting up the project without Docker

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#185]
Sometimes running docker might prove difficult (i.e. Windows machines without virtualization).
For times like these, a set of instructions on how to set-up the project without Docker are vital.

These instructions can also reference other README files from within the project (i.e. Client instructions in `./client`, API in `./api`). The main idea is that they should be the starting point and should direct a first-time contributor in the right direction.

**Comment by myshy93** [comment]
I will try to do it
