### ISSUE TITLE
Main menu moves down

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#290]
**Expected:** 
The menu becomes a drop-down when there is not enough space to fit together with the logo.

**Actual:**
When changing the size of the window, the menu moves down as to not overlap with the logo. While another solution would be to also move the description & the rest of the body out of the way, that is part of another issue (check #291).

![image](https://user-images.githubusercontent.com/2820084/82588395-64b85d00-9ba3-11ea-93af-9d157f7bf915.png)

**Comment by vladplesu** [comment]
Hello, I can take this one,
