### ISSUE TITLE
Main description overlaps with the menu

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#291]
**Expected:**
The main description does not overlap with other elements of the UI. In case the menu moves lower than its normal position, the rest of the body will also move.

**Actual:**
When changing the size of the window, the menu moves down and overlaps with the main description. While another solution would be to minimize the menu when not enough space is available, that is part of another issue (check #290).

![image](https://user-images.githubusercontent.com/2820084/82588159-09866a80-9ba3-11ea-972d-4d63ba770556.png)

**Comment by vladplesu** [comment]
Hello, I can take this one.

**Comment by tudoramariei** [comment]
Closed by #355
