### ISSUE TITLE
[Users] Build login form

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/seismic-risc#3]
As an admin user for the project I need to be able to login to the admin platform.
A simple login form needs to be made available, that will display a form containing username/email and password.

For the look and feel of the UI check out https://www.figma.com/file/qOyFrU8T6LXnJw7YcoVW85/Seismic-Risk?node-id=0%3A1

**Comment by cnstlungu** [comment]
taking this one

**Comment by RaduCStefanescu** [comment]
The login form is implemented, and the login functionality works, but I will leave this issue open as the frontend needs to be designed according to the UX.
