### ISSUE TITLE
[client] Make use of the API to get search data

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#317]
The search bar implemented in the UI is currently not connected to any API endpoint. When using the search bar, results should be returned from the endpoint implemented in #308 

To make a search query, the following endpoint should be accessed:
```api/v1/buildings/search?query=<text>```
The `<text>` attribute is the address used to search.

**Comment by vladplesu** [comment]
Hello! I can take this one.

**Comment by vladplesu** [comment]
Is this a good way to show the results of the search ?

The matched results will be shown in a list and each item will show the address, the postal code and a button to center the marker on the map and show all the details of the selected item.

![image](https://user-images.githubusercontent.com/22684808/94357328-a2247e00-00a0-11eb-90ef-853e114b61f7.png)
