### ISSUE TITLE
[admin] Add a language switcher in the admin interface

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#336]
Internationalisation was implemented for the Django codebase through #292 but to go from one language to another you need to manually change the URL.

A language switcher would help to allow any user to change between languages easily.

**Comment by tudoramariei** [comment]
I discussed with @francisc-czobor and he's able to take this issue

**Comment by francisc-czobor** [comment]
🙋‍♂️

**Comment by francisc-czobor** [comment]
this issue should be closed. my pr is already merged

**Comment by tudoramariei** [comment]
Right! A `closes #issue_number` would make closing the PR also close the issue. I didn't notice there wasn't such a statement 😅
