### ISSUE TITLE
[api] Create API endpoint for the statistics

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#337]
Create an endpoint to expose the statistics in the following form:
``` JSON
{
    "people_under_risk": <int>,
    "evaluated_buildings": <int>,
    "consolidated_buildings": <int>
}
```

- [ ] new URL endpoint of the type `/api/v1/statistics/`
- [ ] the data `people_under_risk` and `consolidated_buildings` should be added/modified throught the admin interface
- [ ] `evaluated_buildings` displays the number of entries in our DB so it should change when new buildings are added

**Comment by francisc-czobor** [comment]
Me and @Raduionutz will do it sometime next week
