### ISSUE TITLE
[Map] Dynamically generate the menu for newly-added pages from the CMS

### ISSUE THREAD

**Issue by catileptic** [code4romania/seismic-risc#36]
The only pages that should always appear in the top menu are "Despre" (About) and "Contact" pages. The rest of the pages should be generated from the pages created in the CMS

https://www.figma.com/file/qOyFrU8T6LXnJw7YcoVW85/Seismic-Risk

**Comment by acelasi7** [comment]
I can take this :),
also I think this feature lives under `site`, not `map`, since the description talks about pages like `Despre`, `Contact`. Maybe the titles needs an update, or maybe I misunderstood it, let me know.

**Comment by tudoramariei** [comment]
Deprecated since the code has moved to https://github.com/code4romania/seismic-risc-client
Not moving it since it's not sure if we will need this feature in the same way
