### ISSUE TITLE
[Users] Seed initial admin username and password

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/seismic-risc#4]
As part of the project setup, we need to seed the username and password for the admin user.

For the look and feel of the UI check out https://www.figma.com/file/qOyFrU8T6LXnJw7YcoVW85/Seismic-Risk?node-id=0%3A1

**Comment by cnstlungu** [comment]
@RaduCStefanescu  This is already covered by Django Admin.  Running 
`python manage.py createsuperuser` starts a small wizards to add the superuser.

**Comment by RaduCStefanescu** [comment]
Implemented in #19
