### ISSUE TITLE
[DevOps] GitHub Actions pipeline for basic checks on master branch for Python

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/seismic-risc#49]
In order to make sure that the `master` branch is safe, we need to put in place a basic pipeline, using GitHub Actions, for running the basic scripts. The purpose of the pipeline is to ensure we don't push broken functionality in the repository.

The pipeline should make sure that the following scripts can be properly run:

`python3 manage.py loaddata buildings`
`python3 manage.py runserver`

**Comment by tudoramariei** [comment]
Currently, a GitHub actions workflow has been set to ensure code quality
It will not, however, ensure that the code doesn't break the master branch
