### ISSUE TITLE
[CMS] Build page content menu in admin panel

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/seismic-risc#5]
In the admin panel the admin user should see a menu for editing page content.

Navigating to this menu item will display a list with all the pages in the platform.

The admin user can navigate to each element in the list and view details for the page content.

For the look and feel of the UI check out https://www.figma.com/file/qOyFrU8T6LXnJw7YcoVW85/Seismic-Risk?node-id=0%3A1

**Comment by tudoramariei** [comment]
I think #25  #26 fixes this issue

**Comment by costibleotu** [comment]
#25
