### ISSUE TITLE
[DevOps] Docker container for running Seismic Risk solution

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/seismic-risc#50]
In order to be able to run the solution, we would need a container running the server.
We are already using a container to run the database.
A Dockerfile should be implemented in order to run both containers.

**Comment by idormenco** [comment]
on it

**Comment by RaduCStefanescu** [comment]
In progress @idormenco

**Comment by radu-diaconescu13** [comment]
Talked to @idormenco  and i will takeover

**Comment by RaduCStefanescu** [comment]
In progress @radu-diaconescu13

**Comment by aramboi** [comment]
Sorry @radu-diaconescu13 for taking over this. 😅
