### ISSUE TITLE
[client] Create a page to display a PDF guide

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#506]
One of the materials presented on the website will be a guide on seismic risk for owners' associations. 
This guide is a PDF which should be displayed in its own page. 

It would be good if the solution allowed for the PDF to be easily replaced if it should be updated, though it is not a must. 

🔗  [Link to the PDF](https://drive.google.com/file/d/1139OVaONdNn8Gp4hwEXxWBdnBsJvTBw3/view)

**Comment by GabrielMajeri** [comment]
Do we want to store that PDF in the repo as an asset, and have the user open it by clicking on a link, or do we want to display it rendered inside the page using something like [`react-pdf`](https://www.npmjs.com/package/react-pdf)?

**Comment by tudoramariei** [comment]
The second option, to have the pdf rendered, would be more fitting. 
We would like to have a simple solution for displaying it while not working with a third-party service like GitHub, Google Drive etc.

**Comment by GabrielMajeri** [comment]
Alright! I want to work on this

**Comment by tudoramariei** [comment]
Great! Assigning it to you!
