### ISSUE TITLE
[client] Create a draft blog post page

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#508]
Using **React** and the data from the API, create a page to display a blog post.
[The project specifications](https://www.figma.com/file/qOyFrU8T6LXnJw7YcoVW85/Seismic-Risk?node-id=0%3A1) have a design for the blog page but it is outdated. The current design for the blog can be found under the `România Vulnerabilă`/`Bucureștiul Vulnerabil` pages. The "recommended articles" section of the blog post should not be implemented at this point.

The blog post should be displayed at the route `/blog/slug`, the slug can be retrieved from the API. The blog post should display the following information from the API:
- title
- image
- tags
- text
- author
- published date

A blog post can be retrieved via the API at the route `http://localhost:8000/api/v1/posts/#`, where # is the number id of the post
For adding new posts, create an admin user, login into the admin interface (`http://localhost:8000/admin/`) and you will find the blog post creation tool.

**Comment by annacs94** [comment]
I would take this issue
