### ISSUE TITLE
Error when building dockerized version with docker-compose on Win10

### ISSUE THREAD

**Issue by clickio** [code4romania/seismic-risc#509]
I've run into an error when trying to build the dockerized version with docker-compose on Win10 using docker with WSL.

I run docker-compose up in the seismic-risc folder and it halts at step 3:
Step 3/10 : RUN apt-get update &&     apt-get install -y --no-install-recommends                     build-essential                     postgresql-client                     libpq-dev                     gettext

with the following error:

E: Failed to fetch http://deb.debian.org/debian/pool/main/g/gcc-defaults/cpp_8.3.0-1_amd64.deb  Bad header line Bad header data [IP: 199.232.138.132 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Fetched 69.5 MB in 40s (1724 kB/s)
ERROR: Service 'api' failed to build : The command '/bin/sh -c apt-get update &&     apt-get install -y --no-install-recommends                     build-essential                     postgresql-client                     libpq-dev                     gettext' returned a non-zero code: 100

I tried splitting it into 3 separated RUN commands and it halts at the first. I tried adding the --fix-missing param to the apt-get update command but it didn't solve the issue.

 I've arrived past this error by appending || true at the end of each RUN command but I'm afraid that this just skipped the missing package and in the end the api docker image doesnt work(client and postgres docker images seem to work).

I looks like a debian install issue, but at the same time if you try in the browser the package is there at that address and it gets downloaded.

Full terminal dump below:

C:\Users\Ionut\Documents\GitHub\seismic-risc>docker-compose up
Creating network "seismic-risc_default" with the default driver
Pulling db (postgres:11)...
11: Pulling from library/postgres
8aff230071c9: Pull complete
4b7067af43b3: Pull complete
a684c6c57155: Pull complete
0e8492701cf8: Pull complete
72314d9ef34e: Pull complete
90cb19bedf37: Pull complete
ccd3c8b3474d: Pull complete
a13817e9decd: Pull complete
db9fc976fc1b: Pull complete
5b8fb784f827: Pull complete
f2ead30d18b9: Pull complete
d4586875faf3: Pull complete
953c743fc793: Pull complete
6fbd6bf01bd7: Pull complete
Digest: sha256:388663a6497e5d1b8f551ad6326d9e3ec142a9cff32575e17e7d0dc3245dd844
Status: Downloaded newer image for postgres:11
Building api
Step 1/10 : FROM python:3.7-slim
3.7-slim: Pulling from library/python
a076a628af6f: Pull complete
a36ca90be64c: Pull complete
420e4b6220ed: Pull complete
772a2b254861: Pull complete
e20e8597a1ca: Pull complete
Digest: sha256:96b68d36ebd785826bc48e6a84e7bd9bbda36a57483d53047ed3c9a53e1fd275
Status: Downloaded newer image for python:3.7-slim
 ---> 1d6cc61f7cb0
Step 2/10 : ARG DEVBUILD
 ---> Running in 742bc7327ea5
Removing intermediate container 742bc7327ea5
 ---> 4267c7614dbc
Step 3/10 : RUN apt-get update &&     apt-get install -y --no-install-recommends                     build-essential                     postgresql-client                     libpq-dev                     gettext
 ---> Running in 3b4a28e19a67
Get:1 http://deb.debian.org/debian buster InRelease [121 kB]
Get:2 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:4 http://security.debian.org/debian-security buster/updates/main amd64 Packages [270 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7907 kB]
Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [7848 B]
Fetched 8424 kB in 5s (1665 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  binutils binutils-common binutils-x86-64-linux-gnu bzip2 cpp cpp-8 dpkg-dev
  g++ g++-8 gcc gcc-8 gettext-base libasan5 libatomic1 libbinutils libbsd0
  libc-dev-bin libc6-dev libcc1-0 libcroco3 libdpkg-perl libedit2 libgcc-8-dev
  libgdbm-compat4 libglib2.0-0 libgomp1 libgssapi-krb5-2 libicu63 libisl19
  libitm1 libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 libldap-2.4-2
  libldap-common liblsan0 libmpc3 libmpfr6 libmpx2 libncurses6 libperl5.28
  libpq5 libquadmath0 libsasl2-2 libsasl2-modules-db libstdc++-8-dev libtsan0
  libubsan1 libxml2 linux-libc-dev make patch perl perl-modules-5.28
  postgresql-client-11 postgresql-client-common sensible-utils xz-utils
Suggested packages:
  binutils-doc bzip2-doc cpp-doc gcc-8-locales debian-keyring g++-multilib
  g++-8-multilib gcc-8-doc libstdc++6-8-dbg gcc-multilib manpages-dev autoconf
  automake libtool flex bison gdb gcc-doc gcc-8-multilib libgcc1-dbg
  libgomp1-dbg libitm1-dbg libatomic1-dbg libasan5-dbg liblsan0-dbg
  libtsan0-dbg libubsan1-dbg libmpx2-dbg libquadmath0-dbg gettext-doc
  autopoint libasprintf-dev libgettextpo-dev glibc-doc gnupg | gnupg2 git bzr
  krb5-doc krb5-user postgresql-doc-11 libstdc++-8-doc make-doc ed
  diffutils-doc perl-doc libterm-readline-gnu-perl
  | libterm-readline-perl-perl libb-debug-perl liblocale-codes-perl
  postgresql-11
Recommended packages:
  fakeroot gnupg | gnupg2 libalgorithm-merge-perl curl | wget | lynx manpages
  manpages-dev libfile-fcntllock-perl liblocale-gettext-perl libglib2.0-data
  shared-mime-info xdg-user-dirs krb5-locales libgpm2 libsasl2-modules
  lsb-release
The following NEW packages will be installed:
  binutils binutils-common binutils-x86-64-linux-gnu build-essential bzip2 cpp
  cpp-8 dpkg-dev g++ g++-8 gcc gcc-8 gettext gettext-base libasan5 libatomic1
  libbinutils libbsd0 libc-dev-bin libc6-dev libcc1-0 libcroco3 libdpkg-perl
  libedit2 libgcc-8-dev libgdbm-compat4 libglib2.0-0 libgomp1 libgssapi-krb5-2
  libicu63 libisl19 libitm1 libk5crypto3 libkeyutils1 libkrb5-3
  libkrb5support0 libldap-2.4-2 libldap-common liblsan0 libmpc3 libmpfr6
  libmpx2 libncurses6 libperl5.28 libpq-dev libpq5 libquadmath0 libsasl2-2
  libsasl2-modules-db libstdc++-8-dev libtsan0 libubsan1 libxml2
  linux-libc-dev make patch perl perl-modules-5.28 postgresql-client
  postgresql-client-11 postgresql-client-common sensible-utils xz-utils
0 upgraded, 63 newly installed, 0 to remove and 2 not upgraded.
Need to get 69.5 MB of archives.
After this operation, 286 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 perl-modules-5.28 all 5.28.1-6+deb10u1 [2873 kB]
Get:2 http://deb.debian.org/debian buster/main amd64 libgdbm-compat4 amd64 1.18.1-4 [44.1 kB]
Get:3 http://deb.debian.org/debian buster/main amd64 libperl5.28 amd64 5.28.1-6+deb10u1 [3894 kB]
Get:4 http://deb.debian.org/debian buster/main amd64 perl amd64 5.28.1-6+deb10u1 [204 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 sensible-utils all 0.0.12 [15.8 kB]
Get:6 http://deb.debian.org/debian buster/main amd64 bzip2 amd64 1.0.6-9.2~deb10u1 [48.4 kB]
Get:7 http://deb.debian.org/debian buster/main amd64 gettext-base amd64 0.19.8.1-9 [123 kB]
Get:8 http://deb.debian.org/debian buster/main amd64 xz-utils amd64 5.2.4-1 [183 kB]
Get:9 http://deb.debian.org/debian buster/main amd64 binutils-common amd64 2.31.1-16 [2073 kB]
Get:10 http://deb.debian.org/debian buster/main amd64 libbinutils amd64 2.31.1-16 [478 kB]
Get:11 http://deb.debian.org/debian buster/main amd64 binutils-x86-64-linux-gnu amd64 2.31.1-16 [1823 kB]
Get:12 http://deb.debian.org/debian buster/main amd64 binutils amd64 2.31.1-16 [56.8 kB]
Get:13 http://deb.debian.org/debian buster/main amd64 libc-dev-bin amd64 2.28-10 [275 kB]
Get:14 http://deb.debian.org/debian buster/main amd64 linux-libc-dev amd64 4.19.160-2 [1416 kB]
Get:15 http://deb.debian.org/debian buster/main amd64 libc6-dev amd64 2.28-10 [2691 kB]
Get:16 http://deb.debian.org/debian buster/main amd64 libisl19 amd64 0.20-2 [587 kB]
Get:17 http://deb.debian.org/debian buster/main amd64 libmpfr6 amd64 4.0.2-1 [775 kB]
Get:18 http://deb.debian.org/debian buster/main amd64 libmpc3 amd64 1.1.0-1 [41.3 kB]
Get:19 http://deb.debian.org/debian buster/main amd64 cpp-8 amd64 8.3.0-6 [8914 kB]
Err:20 http://deb.debian.org/debian buster/main amd64 cpp amd64 4:8.3.0-1
  Bad header line Bad header data [IP: 199.232.138.132 80]
Get:21 http://deb.debian.org/debian buster/main amd64 libcc1-0 amd64 8.3.0-6 [46.6 kB]
Get:22 http://deb.debian.org/debian buster/main amd64 libgomp1 amd64 8.3.0-6 [75.8 kB]
Get:23 http://deb.debian.org/debian buster/main amd64 libitm1 amd64 8.3.0-6 [27.7 kB]
Get:24 http://deb.debian.org/debian buster/main amd64 libatomic1 amd64 8.3.0-6 [9032 B]
Get:25 http://deb.debian.org/debian buster/main amd64 libasan5 amd64 8.3.0-6 [362 kB]
Get:26 http://deb.debian.org/debian buster/main amd64 liblsan0 amd64 8.3.0-6 [131 kB]
Get:27 http://deb.debian.org/debian buster/main amd64 libtsan0 amd64 8.3.0-6 [283 kB]
Get:28 http://deb.debian.org/debian buster/main amd64 libubsan1 amd64 8.3.0-6 [120 kB]
Get:29 http://deb.debian.org/debian buster/main amd64 libmpx2 amd64 8.3.0-6 [11.4 kB]
Get:30 http://deb.debian.org/debian buster/main amd64 libquadmath0 amd64 8.3.0-6 [133 kB]
Get:31 http://deb.debian.org/debian buster/main amd64 libgcc-8-dev amd64 8.3.0-6 [2298 kB]
Get:32 http://deb.debian.org/debian buster/main amd64 gcc-8 amd64 8.3.0-6 [9452 kB]
Get:33 http://deb.debian.org/debian buster/main amd64 gcc amd64 4:8.3.0-1 [5196 B]
Get:34 http://deb.debian.org/debian buster/main amd64 libstdc++-8-dev amd64 8.3.0-6 [1532 kB]
Get:35 http://deb.debian.org/debian buster/main amd64 g++-8 amd64 8.3.0-6 [9752 kB]
Get:36 http://deb.debian.org/debian buster/main amd64 g++ amd64 4:8.3.0-1 [1644 B]
Get:37 http://deb.debian.org/debian buster/main amd64 make amd64 4.2.1-1.2 [341 kB]
Get:38 http://deb.debian.org/debian buster/main amd64 libdpkg-perl all 1.19.7 [1414 kB]
Get:39 http://deb.debian.org/debian buster/main amd64 patch amd64 2.7.6-3+deb10u1 [126 kB]
Get:40 http://deb.debian.org/debian buster/main amd64 dpkg-dev all 1.19.7 [1773 kB]
Get:41 http://deb.debian.org/debian buster/main amd64 build-essential amd64 12.6 [7576 B]
Get:42 http://deb.debian.org/debian buster/main amd64 libglib2.0-0 amd64 2.58.3-2+deb10u2 [1258 kB]
Get:43 http://deb.debian.org/debian buster/main amd64 libicu63 amd64 63.1-6+deb10u1 [8300 kB]
Get:44 http://deb.debian.org/debian buster/main amd64 libxml2 amd64 2.9.4+dfsg1-7+deb10u1 [689 kB]
Get:45 http://deb.debian.org/debian buster/main amd64 libcroco3 amd64 0.6.12-3 [145 kB]
Get:46 http://deb.debian.org/debian buster/main amd64 libncurses6 amd64 6.1+20181013-2+deb10u2 [102 kB]
Get:47 http://deb.debian.org/debian buster/main amd64 gettext amd64 0.19.8.1-9 [1303 kB]
Get:48 http://deb.debian.org/debian buster/main amd64 libbsd0 amd64 0.9.1-2 [99.5 kB]
Get:49 http://deb.debian.org/debian buster/main amd64 libedit2 amd64 3.1-20181209-1 [94.0 kB]
Get:50 http://deb.debian.org/debian buster/main amd64 libkeyutils1 amd64 1.6-6 [15.0 kB]
Get:51 http://deb.debian.org/debian buster/main amd64 libkrb5support0 amd64 1.17-3+deb10u1 [65.8 kB]
Get:52 http://deb.debian.org/debian buster/main amd64 libk5crypto3 amd64 1.17-3+deb10u1 [122 kB]
Get:53 http://deb.debian.org/debian buster/main amd64 libkrb5-3 amd64 1.17-3+deb10u1 [369 kB]
Get:54 http://deb.debian.org/debian buster/main amd64 libgssapi-krb5-2 amd64 1.17-3+deb10u1 [158 kB]
Get:55 http://deb.debian.org/debian buster/main amd64 libsasl2-modules-db amd64 2.1.27+dfsg-1+deb10u1 [69.1 kB]
Get:56 http://deb.debian.org/debian buster/main amd64 libsasl2-2 amd64 2.1.27+dfsg-1+deb10u1 [106 kB]
Get:57 http://deb.debian.org/debian buster/main amd64 libldap-common all 2.4.47+dfsg-3+deb10u4 [89.8 kB]
Get:58 http://deb.debian.org/debian buster/main amd64 libldap-2.4-2 amd64 2.4.47+dfsg-3+deb10u4 [224 kB]
Get:59 http://deb.debian.org/debian buster/main amd64 libpq5 amd64 11.9-0+deb10u1 [167 kB]
Get:60 http://deb.debian.org/debian buster/main amd64 libpq-dev amd64 11.9-0+deb10u1 [163 kB]
Get:61 http://deb.debian.org/debian buster/main amd64 postgresql-client-common all 200+deb10u4 [85.1 kB]
Get:62 http://deb.debian.org/debian buster/main amd64 postgresql-client-11 amd64 11.9-0+deb10u1 [1401 kB]
Get:63 http://deb.debian.org/debian buster/main amd64 postgresql-client all 11+200+deb10u4 [61.1 kB]
E: Failed to fetch http://deb.debian.org/debian/pool/main/g/gcc-defaults/cpp_8.3.0-1_amd64.deb  Bad header line Bad header data [IP: 199.232.138.132 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Fetched 69.5 MB in 40s (1724 kB/s)
ERROR: Service 'api' failed to build : The command '/bin/sh -c apt-get update &&     apt-get install -y --no-install-recommends                     build-essential                     postgresql-client                     libpq-dev                     gettext' returned a non-zero code: 100

**Comment by johnyzv** [comment]
This is my output from todays `develop` branch
```
C:\Work\Code4Romania\seismic-risc>docker-compose build --pull
...
Building api
Step 1/10 : FROM python:3.7-slim
3.7-slim: Pulling from library/python
a076a628af6f: Pull complete
a36ca90be64c: Pull complete
420e4b6220ed: Pull complete
772a2b254861: Pull complete
e20e8597a1ca: Pull complete
...
Get:63 http://deb.debian.org/debian buster/main amd64 postgresql-client all 11+200+deb10u4 [61.1 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 69.5 MB in 7s (9484 kB/s)
```

✅ Image build ok for the api service.

I checked that the hashes for the python image layers are the same for both of us for `python:3.7-slim`

My two cents on this is that maybe this was a false positive on the debian.

My environment: Win10 (20H2 - 19042.782) Docker Desktop with wsl2
```
>docker -v
Docker version 20.10.2, build 2291f61
>docker-compose -v
docker-compose version 1.27.4, build 40524192
```

If this can be reproduced by someone else either on windows/linux, I am more than happy to contribute.

Cheers,
Johny

**Comment by catileptic** [comment]
Closing this. @clickio, let me know if you encounter any further issues.
