### ISSUE TITLE
[DevOps] Deploy image to Docker Hub and run image on AWS ECS

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/seismic-risc#51]
Setup a pipeline using Github Actions to:
- deploy docker image to ECR
- create ECS tasks to run image on EC2

**Comment by LucianU** [comment]
@RaduCStefanescu, I can make a Terraform setup that automates all this. Terraform can also handle creating ECR, ECS and EC2. This is an example of the final result, without the Haskell and Nix part:
https://www.williamyaoh.com/posts/2019-04-09-deploying-haskell-with-ecs-and-nix.html

**Comment by RaduCStefanescu** [comment]
Hi @LucianU 
Pretty awesome you want to contribute to this issue.
Well, my thoughts were about using Ansible for this task? What do you think?

**Comment by LucianU** [comment]
If all the other infrastructure provisioning code is in Ansible, then I understand why you would want to keep it that way.

My reasons for preferring Terraform now over Ansible are as follows:

Ansible doesn't keep a state of the infrastructure while Terraform does. 
What do I mean by this? Let's say you have an Ansible task that creates 1 server. If you run the task twice, you get two servers, unless you assign a label to that server and check that it exists before you run the task. 

Terraform keeps a snapshot of your entire infrastructure in a file which you can share with others. If you add a server resource to your Terraform files, it will make sure that exists. If it exists, it won't do anything. Every time you run `terraform apply`, it will show you the changes it will make.

There is another consequence to Ansible's lack of state. If you delete a task, Ansible doesn't know to clean up the resource defined by that task. So you're left with junk around, unless you remember to delete it manually.

With Terraform, if you delete a resource from the config file, Terraform will delete it from the infrastructure.

Again, if all infrastructure code is in Ansible, I can understand why you don't want to add a second tool. But if there isn't much Ansible code, I recommend using Terraform.

**Comment by LucianU** [comment]
Considering the conversation we had on Slack, I'll go ahead and start working on a setup that uses Terraform to provision the needed AWS resources.

**Comment by RaduCStefanescu** [comment]
Assigned @LucianU 
Thank you!

**Comment by RaduCStefanescu** [comment]
In progress @LucianU

**Comment by LucianU** [comment]
@RaduCStefanescu, I have a few questions:
- do we already have an ECR or should Terraform create one?
- what type of EC2 instance should we create?

**Comment by RaduCStefanescu** [comment]
@LucianU 
- Based on our recent discussions regarding DevOps I would like to use Docker Hub for a repository for our images
- The EC2 instances should be `t2.micro`

**Comment by LucianU** [comment]
@RaduCStefanescu, can I get access to an AWS account where I can test the Terraform setup?

**Comment by RaduCStefanescu** [comment]
@LucianU I will come back with the details in Slack
