### ISSUE TITLE
[api] Display the author's name in the blog post 

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#510]
The blog post author's `first name` and `last name` should be returned for each post.
Currently, the `api/posts` endpoint returns the author's ID (e.g. `"author": 1,`), instead, for that post the value returned should return the following information: 
``` 
"firstName": "Seismic", 
"lastName": "Risk" 
```

**Comment by mateesville93** [comment]
Hi @tudoramariei 
It's ok if it returns something like this:
` 
  "author": "username",
  "author_first_name": "John",
  "author_last_name": "Doe",
`

**Comment by tudoramariei** [comment]
Looks quite good. 
Though I'm not sure about displaying the username. I think it's best if we left it private (at least for now).
