### ISSUE TITLE
[client] Customize map markers by their category 

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#526]
Pins should have **different shapes** & **different colours** based on the risk category of the building they show. 

The customization should allow for the representation of 9 categories: 
> `U1`, `U2`, `U3`, `U4`, `RS I`, `RS II`, `RS III`, `RS IV`, `N/A`

🔗   [The location of the marker implementation is here](https://github.com/code4romania/seismic-risc/blob/develop/client/src/components/HereMapInteractive.js#L76)

**Comment by myshy93** [comment]
I will take it.
Any preferences for pin colors?

**Comment by myshy93** [comment]
Is this ok?

![image](https://user-images.githubusercontent.com/11949565/109427703-49189780-79fc-11eb-8fb9-ab033d7639af.png)

**Comment by myshy93** [comment]
I also managed to add risk class name on marker.

![image](https://user-images.githubusercontent.com/11949565/109429238-59804080-7a03-11eb-8f6c-196b7816917e.png)

**Comment by tudoramariei** [comment]
We don't currently have any specifications for the colours. We were looking for the ability to customize markers. 
This seems to tick the box. 😄
