### ISSUE TITLE
[client] Change behaviour when selecting a marker

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#544]
A marker can be selected by clicking on it or through the address search feature. At this point, when selecting a marker, the map zooms at a level where there is a substantial density of markers and doesn't allow for telling which marker is which.

A selected marker should be highlighted on the map differently from the rest of them. The way the marker is highlighted might change in the future if the design updates. (this applies for both search and clicking)

When a marker is clicked, the zoom level and position of the map should not change. Panning and zooming should only happen when searching for a marker or manually by the user. Clicking on a marker moves the map to its position and zooms to a specific position.

Default zoom level when selecting a marker: 
![Screenshot 2021-02-13 at 08 42 32](https://user-images.githubusercontent.com/2820084/107843879-6c75fc80-6dd7-11eb-8e2d-548eadc3f69e.png)

**Comment by annacs94** [comment]
I would take this
