### ISSUE TITLE
[client] Implement clustering for markers

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#547]
Add a clustering layer for map pins. For now, we don't have any specifications regarding the radius or other specifications so the only guideline is `common sense`. 

If you have any questions, just comment here.

Docs: https://developer.here.com/documentation/examples/maps-js/clustering/marker-clustering

**Comment by annacs94** [comment]
I would take this issue

**Comment by tudoramariei** [comment]
Thanks a lot! I've assigned it to you 😄
