### ISSUE TITLE
Create 404 page and route it

### ISSUE THREAD

**Issue by catileptic** [code4romania/seismic-risc#561]
On the mobile version, the left-side logo should come first and the text should be beneath it. 

On tablet and beyond, the two are on the same line, centred horizontally, padded. 

[Link to the specs](https://www.figma.com/file/dUL9ybnag2LhQpicJseFaH/Seismic-Risk?node-id=1637%3A497)

![404](https://user-images.githubusercontent.com/14028425/109186520-acef5600-7799-11eb-86ce-04e521b75d18.png)

**Comment by myshy93** [comment]
I will take this

**Comment by myshy93** [comment]
how much padding for top/bottom?

**Comment by tudoramariei** [comment]
@myshy93 Forgot to add the link to the specifications. I hope the Figma designs have all the information you need 
https://www.figma.com/file/dUL9ybnag2LhQpicJseFaH/Seismic-Risk?node-id=1637%3A497

**Comment by myshy93** [comment]
The message should be available in English also?

**Comment by tudoramariei** [comment]
Yes, it should. And since we should have made the text available, here it is 😅 

> **We are sorry**
> We can not find the page you are looking for. Please go back to the main page and start your search again or navigate through the rest of our platform with the help of the upper menu.
> If you encounter other issues, please send us an e-mail at ...

**Comment by myshy93** [comment]
development done, a have to add some test and is done
