### ISSUE TITLE
Add about page

### ISSUE THREAD

**Issue by catileptic** [code4romania/seismic-risc#564]
Here's the mock ([link to the specs](https://www.figma.com/file/dUL9ybnag2LhQpicJseFaH/Seismic-Risk?node-id=1643%3A0)): 
![About page](https://user-images.githubusercontent.com/14028425/109196120-fcd31a80-77a3-11eb-8daf-1a7ed67ebb17.png)

- the TFSG box will display the elements on top of each other on mobile
- the bottom logo row will also display the elements on top of each other on mobile

Here's the MKBT logo that leads to mkbt.ro:
![5030](https://user-images.githubusercontent.com/14028425/109196134-ffce0b00-77a3-11eb-9503-228ae9025cb6.png)

**Comment by CatalinCsnMaster** [comment]
I'll take this one
