### ISSUE TITLE
Update the detailed information panel

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#568]
[Link to the specifications](https://www.figma.com/file/dUL9ybnag2LhQpicJseFaH/Seismic-Risk?node-id=1637%3A289)
(the value for `Clasa de risc` should be U3, the `risk_category` API variable while the `Anul expertizei tehnice` should be the value of the `examination_year` variable)

![Screenshot 2021-02-26 at 10 32 38](https://user-images.githubusercontent.com/2820084/109275851-f5505780-781d-11eb-89b0-eb3540c44afd.png)

**Comment by Kerosz** [comment]
Seems like this already has the right values
![image](https://user-images.githubusercontent.com/31253154/110100027-a0c35400-7daa-11eb-837b-858b211c2bd0.png)
![image](https://user-images.githubusercontent.com/31253154/110100062-ab7de900-7daa-11eb-8d45-ac3c7de4bce9.png)

**Comment by myshy93** [comment]
i will take it

**Comment by tudoramariei** [comment]
@Kerosz the values aren't wrong, but the design has changed. You can see a screenshot and the specs in the initial comment from the issue.

**Comment by myshy93** [comment]
`Total surface` is still needed ? I don't see it in specifications

**Comment by tudoramariei** [comment]
No, it's not needed anymore
