### ISSUE TITLE
Create an API endpoint that returns partial info on buildings

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#573]
Multiple views should be available for the buildings endpoints which should:
1. return for **all the buildings** only the `general_id`, `lat`, `lng`, and `risk_category` 
2. return for **one specific building** all the necessary fields (as it currently happens)

The downside is that this would require changes to the client makes individual requests for each building that is selected.

**Comment by JustBeYou** [comment]
If no one is working on this I think I could do it. 
By the way, are you sure that the client would need to be modified too? I see that it already does individual requests when you click on a building.
