### ISSUE TITLE
Implement Django REST framework

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#58]
To have a more streamlined communication between front-end and back-end, a better, more flexible API should be created to handle the information

**Comment by tudoramariei** [comment]
Assigned to @danniel

**Comment by andreisima** [comment]
[API Repo](https://github.com/andreisima/seismic-risc/tree/master/seismic_site/api)
Thoughts?

**Comment by RaduCStefanescu** [comment]
Hi @andreisima 
Thank you for the contribution.

To make it easier for us to follow your changes, how about opening a Pull Request with the changes in your branch?

**Comment by andreisima** [comment]
Hi @RaduCStefanescu 
I will read your PR rules, and see what PEP rules you are following.
Then I will open a PR
