### ISSUE TITLE
[Map] Selected pin is hidden under building details on mobile

### ISSUE THREAD

**Issue by myshy93** [code4romania/seismic-risc#592]
**Description:** In mobile version when selecting a building on map by click on it, the map zooms, the building info panel appears over the selected pin. The user can not see any more where where is placed the building on map while it read info about it.

**Steps to reproduce:**
1. Open the home page in Chrome Dev Tools and select mobile view.
2. Chose any mobile screen (iPhone, S5, any...)
3. Click on a building marker.

**Actual outcome:**

Map centers and the pin is hidden under info panel. 

![image](https://user-images.githubusercontent.com/11949565/110098013-5fca4000-7da8-11eb-87b4-cdf4a8bea83a.png)

**Expected outcome:**

On mobile version the map should focus the selected marker some where so it can be visible when info panel rendes.

![image](https://user-images.githubusercontent.com/11949565/110098155-88523a00-7da8-11eb-8c52-ea6ed311026c.png)

**Comment by annacs94** [comment]
I can take this
