### ISSUE TITLE
[Mobile] Info cards are not mobile friendly 

### ISSUE THREAD

**Issue by myshy93** [code4romania/seismic-risc#594]
**Description:** In mobile the text in info cards goes outside the borders.

**Steps to reproduce:**

1. Open the home page in Chrome Dev Tools and select mobile view.
2. Chose any mobile screen (iPhone, S5, any...)

**Actual outcome:**
![image](https://user-images.githubusercontent.com/11949565/110100659-542c4880-7dab-11eb-90c5-249d19a11751.png)

**Expected outcome:**

The renders inside the box. Maybe put the cards stacked instead of inline.

**Comment by vladplesu** [comment]
Hello, I can take this one.
