### ISSUE TITLE
[client] Add the latest 3 blog posts on the main page

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#599]
[Link to specs](https://www.figma.com/file/dUL9ybnag2LhQpicJseFaH/Seismic-Risk?node-id=2%3A2)
Create a component to display the preview of the latest 3 blog posts on the main page.
The preview should contain the `title` of the post and the `cover photo`.

![Screenshot 2021-03-08 at 16 15 20](https://user-images.githubusercontent.com/2820084/110332810-7d5a0c80-8029-11eb-8df4-98bec8fc23af.png)

**Comment by myshy93** [comment]
I will take it

**Comment by myshy93** [comment]
the blue color on top is for hover ?

**Comment by tudoramariei** [comment]
Yes, I think it is
