### ISSUE TITLE
[client] Change blog design and behaviour

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#624]
The blog posts on the blog main page should be sorted `descending` by `published_date` and not by `created_date`.

Some changes should also be made to the blog main page to make it fit the rest of the design better:

- [ ] the background of an item should change on hover to `#FAFAFA`
- [ ] the whole `blog-item` row should be clickable
- [ ] the `read more` button should be removed 

The behaviour would be similar to that of the blog preview in #621 albeit with a slightly different design.

**Comment by vladplesu** [comment]
Hello, I can take this one.
