### ISSUE TITLE
[client] Create the form for adding new buildings

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#625]
[Link to specs (sections: _Form page_ & _Form success_)](https://www.figma.com/file/dUL9ybnag2LhQpicJseFaH/Seismic-Risk?node-id=1642%3A2)

POST/OPTIONS endpoint: `/api/v1/buildings/public_create/`

Based on the design from the specifications, create a form to allow users to add buildings to the database. 
The form should request the following fields:
- street (mapped to address in the API)
- street number (mapped to post_code in the API)
- locality
- county
- height regime
- risk category - dropdown selector, run an `OPTIONS` request to the endpoint for the data

If the POST was successful, redirect the user to the `Form success` page.

Later Edit: the design for a dropdown field is [in the bottom left part of the design](https://www.figma.com/file/dUL9ybnag2LhQpicJseFaH/Seismic-Risk?node-id=1469%3A635)

**Comment by myshy93** [comment]
I'll take it

**Comment by myshy93** [comment]
Please review design specifications because there is no 'submit' button

**Comment by myshy93** [comment]
Some fields are required by the API and not present in Form. Can I reword `public_create` endpoint so they will work ok together ?
![image](https://user-images.githubusercontent.com/11949565/111956217-31ac6600-8af3-11eb-90a5-3a11243de4f3.png)

**Comment by tudoramariei** [comment]
The fields that should appear in the form are mentioned in the first comment of the issue. They are: 

> **street** (mapped to address in the API)
> **street number** (mapped to post_code in the API)
> **locality**
> **county**
> **height regime**
> **risk category** - dropdown selector, run an OPTIONS request to the endpoint for the data

Also, here is [a link to the dropdown design](https://www.figma.com/file/dUL9ybnag2LhQpicJseFaH/Seismic-Risk?node-id=1469%3A635). Here you can also find the design for the submit button. 
Right now we can go with that design using white text and the Seismic Risc orange (#EE741B) instead of that grey. And use #C45E16 as a highlight when clicking the button.

**Comment by myshy93** [comment]
sorry I an quite busy this period :( , please assig this to other

**Comment by tudoramariei** [comment]
Thanks for letting us know @myshy93 
Good luck with your work 😄

**Comment by vladplesu** [comment]
Hello! I can take this one.
