### ISSUE TITLE
Add map input for the form

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#645]
Add a map using `Here Maps` to get the coordinates of the building

The map field should be placed under the address field (after the `County`)
After the user fills in the address, they should be able to click/tap a button to [get the initial position of the marker based on the address](http://jsfiddle.net/gh/get/jquery/2.1.0/heremaps/jsfiddle-github/tree/master/geocode-a-location-from-address) (also, the same example but just [the code](https://github.com/heremaps/maps-api-for-javascript-examples/tree/master/geocode-a-location-from-address))

The user should then be able to pan & zoom the map and move the marker on a tap/click
The coordinates will be returned from the position of the marker 
[JS Fiddle example for Calculating a Location from a Mouse Click](http://jsfiddle.net/gh/get/jquery/2.1.0/heremaps/jsfiddle-github/tree/master/position-on-mouse-click) and the same example but just the [code](https://github.com/heremaps/maps-api-for-javascript-examples/tree/master/position-on-mouse-click)

**Comment by annacs94** [comment]
I would take this
