### ISSUE TITLE
Update map full info panel design

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#660]
Link to specs: [https://www.figma.com/file/dUL9ybnag2LhQpicJseFaH/Seismic-Risk?node-id=2066%3A4](https://www.figma.com/file/dUL9ybnag2LhQpicJseFaH/Seismic-Risk?node-id=2066%3A4432)

Change the design for the `BuildingDetails` and `SearchResults` panels to fit the new specifications

The Figma prototype is missing a close button. It should be in the upper-right corner, as an "X" icon, the same colour as the title.

While the functionality _isn't there_ for the `supplementary information` and `see images` components, please add them while taking the following notes into account:
- `supplementary information`/`adaugă informații`: the button should just take the user to the `/adauga-cladire` section;
- `see images`/`vezi imagini`: the button should only show up if the building has any images attached to it. If the buildings have any images attached, clicking the link should display a modal view where the user can view each image and navigate among them using the left and right arrows on their keyboard, or left and right arrow buttons inside the modal view.

On mobile, the elements in this panel should all be stacked on one column.

![Screenshot 2021-05-17 at 09 36 06](https://user-images.githubusercontent.com/2820084/118442590-73bce700-b6f3-11eb-96ce-546857869eaa.png)

**Comment by cipick** [comment]
🙋
