### ISSUE TITLE
Update the design of pages to the new specifications

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#661]
Link to specs: [https://www.figma.com/file/dUL9ybnag2LhQpicJseFaH/Seismic-Risk?node-id=2066%3A0](https://www.figma.com/file/dUL9ybnag2LhQpicJseFaH/Seismic-Risk?node-id=2066%3A0)

The new page structure is composed of:
- a white (#FFFFFF) banner with a title, some text, an image, and (maybe) a couple of buttons;
- a grey (#E5E5E5) section with the actual contents of the page extending to but not including the footer

Pages to be changed: [Homepage](https://www.figma.com/file/dUL9ybnag2LhQpicJseFaH/Seismic-Risk?node-id=2066%3A4)[1], [Blog listing](https://www.figma.com/file/dUL9ybnag2LhQpicJseFaH/Seismic-Risk?node-id=2066%3A2967), [Blog post](https://www.figma.com/file/dUL9ybnag2LhQpicJseFaH/Seismic-Risk?node-id=2066%3A3379)[2], [About page](https://www.figma.com/file/dUL9ybnag2LhQpicJseFaH/Seismic-Risk?node-id=2066%3A3642), [Form input page](https://www.figma.com/file/dUL9ybnag2LhQpicJseFaH/Seismic-Risk?node-id=2066%3A2458)[3], [Form thank you page](https://www.figma.com/file/dUL9ybnag2LhQpicJseFaH/Seismic-Risk?node-id=2066%3A3838)

:warning: **IMPORTANT NOTES:**

1. the homepage should use the desktop image for both desktop and mobile
2. the blog post banner should also contain details from the blog post (title, author, published date)
3. the modifications for the form should be on the design only, the form structure and its fields are not covered by the scope of this issue

**Comment by vladplesu** [comment]
Hello! I can take this one.
