### ISSUE TITLE
Add a map to display the coordinates of each building in the admin

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#669]
Override the default Django admin template for buildings change. Extend the template to include a map using the Here! Maps API to display the coordinates if they both exist. 

The map should allow the pin to move and update the existing coordinates.
The map should help the admins easily find the location of the buildings.

Helpful Django docs: https://docs.djangoproject.com/en/3.2/ref/contrib/admin/#overriding-default-admin-site
How to get HERE developer credentials: https://developer.here.com/tutorials/getting-here-credentials/
Override by creating the following file: `templates/admin/buildings/building/change_form.html`
The page path: `/admin/buildings/building/ID/change/`

**Comment by juliageek** [comment]
I volunteer! http://gph.is/1O9NiIU
