### ISSUE TITLE
Add CAPTCHA verification for the add building form

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#670]
Before submitting a new building, a user should be given a CAPTCHA to complete.

After looking at multiple solutions, hCAPTCHA seems to be a better solution for this task. 
hCAPTCHA seems to be more privacy-focused without compromises on performance or the ease of implementation.
🔗 [hCAPTCHA documentation](https://docs.hcaptcha.com/)

**Comment by damianr13** [comment]
I would like to be working on this!

**Comment by tudoramariei** [comment]
All yours! 🙇
