### ISSUE TITLE
[CMS] Create general style for the all articles ("toate articolele") interface

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#69]
The page should contain a list of existing articles with the data from the UX specifications

Current page address: `/admin/cms/page/`
UX Specs: https://www.figma.com/file/qOyFrU8T6LXnJw7YcoVW85/Seismic-Risk?node-id=588%3A256

**Comment by luchianvictor** [comment]
I would start this.

**Comment by tudoramariei** [comment]
It's yours, @luchianvictor 
Thanks! 😄

**Comment by tudoramariei** [comment]
Closing for the same reason as #68
