### ISSUE TITLE
Extend the form with the fields from the new specifications

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#692]
Extend the `new building` form to add the missing fields from the design

⚠️ Do not delete any of the existing fields, **even if they do not appear in the design**
ℹ️ All the new fields should be added between the **risk class input** and the **CAPTCHA verification**
🌐 The form must be internationalized, available in both English 🇬🇧  and Romanian 🇷🇴 

Specifications: https://docs.google.com/spreadsheets/d/1PbEHJWkgr2gDBz7ynqy4ia_po6cAbW_dcByRVl1fxks
Design: https://www.figma.com/file/dUL9ybnag2LhQpicJseFaH/Seismic-Risk?node-id=2630%3A3912
API schema: https://api-seismicrisc.code4.ro/api/v1/schema/swagger-ui/
Form endpoint: https://api-seismicrisc.code4.ro/api/v1/buildings/public_create/ (`OPTIONS` request)

**Comment by tudoramariei** [comment]
Some fields have not been implemented in the back-end. Still, a partial implementation with the current fields is also useful at this point.

**Comment by dragosvecerdea** [comment]
Salutare. As vrea sa lucrez la acest issue. Mai este de actualitate?

**Comment by tudoramariei** [comment]
Sigur, Dragos! Te asignez, atunci, la issue 😄

**Comment by vladplesu** [comment]
Hello! I can take this one.

**Comment by dragosvecerdea** [comment]
Please do @vladplesu. Thanks! 
@tudoramariei May we have it reassigned to Vlad ?
