### ISSUE TITLE
Internationalise the interface

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#70]
All the text displayed should be multilingual, allowing us to deploy the application in different languages
This also allows the display of Romanian strings while at the same time allowing developers to easily understand what those strings represent

Languages supported: en-GB (code language), ro-RO

Mock text can be used in the beginning to not spend much time on translating everything

Django i18n docs: https://docs.djangoproject.com/en/3.0/topics/i18n/

**Comment by Tudor95** [comment]
I am interested and will investigate the issue, talked to @tudoramariei

**Comment by tudoramariei** [comment]
Give it a go! If you need any help, you can also write on the Slack channel

**Comment by RaduCStefanescu** [comment]
Hey @Tudor95 thank you for your interest in this issue.
Is everything ok, will you be making a PR?

**Comment by danniel** [comment]
I will work on this issue today.
