### ISSUE TITLE
Add on-hover display for "risc seismic" element

### ISSUE THREAD

**Issue by catileptic** [code4romania/seismic-risc#705]
When a user hovers over the "risc seismic" element, a text box should be displayed, explaining the term. 
On mobile, tapping the element will bring up the same text box, and tapping anywhere else on the screen will close the text box. 

Until the content for this element is done, please fill it with lorem ipsum. 
![image](https://user-images.githubusercontent.com/14028425/128768424-4e562c7d-5dea-4b29-ac78-8b5718a85470.png)

**Comment by danmolloy** [comment]
Hi catileptic,

I think I'd like to help you - I'm just having trouble finding this element in the code. Could you please advise me which file it's in? 

Very best,
Dan

**Comment by tudoramariei** [comment]
hey @danmolloy!
You can find the item right here, inside of a `span` 
https://github.com/code4romania/seismic-risc/blob/231cd1abbf177dc1b6bf0e1876a2401dd05bd6d8/client/src/containers/home/SearchFragment.js#L52

If I didn't understand right and you're looking for something else, please let me know 😄

**Comment by danmolloy** [comment]
Cool. Yes, please assign me this issue 😁

**Comment by CatalinCsnMaster** [comment]
Hello!

Can [Tippy.js](https://atomiks.github.io/tippyjs/) be used for this task?
