### ISSUE TITLE
[Discussion] API and client interaction in the blog

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#71]
Blog posts are generated in the same way as other pages through the Django CMS
The Django REST API should be able to return these articles 
The React client should be able to add a style over them

We would need to form a better opinion on how such an architecture might look
Anyone with experience in this area is welcome to contribute to the discussion

**Comment by iuliux** [comment]
Will start by making an API endpoint for Pages which should help start the frontend part.

**Comment by aramboi** [comment]
As discussed with @RaduCStefanescu, I will start working on the blog app. I have already most of the work done for a personal project, just need to adapt it for the rest framework and I will post a PR in the following week or so.

**Comment by tudoramariei** [comment]
Thanks a lot for the help, @aramboi! I'm looking forward to seeing your work 😄
