### ISSUE TITLE
Redesign the UI for the new project branding

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#718]
The project name and logo have changed from `Seismic Risc` to `Bulina Roșie`.
The new design exists in Figma; a summary of the changes needed are described below.

⚠️ Make sure text updates are internationalized.

## General changes

- [ ] change the font from Titillium Web to [Source Sans Pro](https://fonts.google.com/specimen/Source+Sans+Pro)
- [ ] the colour scheme changes from the orange highlights to #EE4036
- [ ] change the design of the banner component
- [ ] change all `Seismic Risc` texts to `Bulina Roșie`
- [ ] the size of the content block (below the banner) has shrunk

## [Header](https://www.figma.com/file/dUL9ybnag2LhQpicJseFaH/Seismic-Risk?node-id=2464%3A77)

- [ ] change the logo to the new Bulina Roșie one [🔗 click for the svg](https://drive.google.com/file/d/1_J8fF3yiJ_hTRwLHfrVJ0eoGXExNAGLS/view?usp=sharing)
- [ ] change `about` -> `about project`
- [ ] update the `add building` button to the new specs

## [Homepage](https://www.figma.com/file/dUL9ybnag2LhQpicJseFaH/Seismic-Risk?node-id=2066%3A4)

- [ ] remove the `add building` and `about project` buttons from the welcome banner
- [ ] tweak the [design of the `risc seismic` button](https://www.figma.com/file/dUL9ybnag2LhQpicJseFaH/Seismic-Risk?node-id=2603%3A4548)
- [ ] change the search help text [to the one from the design](https://www.figma.com/file/dUL9ybnag2LhQpicJseFaH/Seismic-Risk?node-id=2603%3A4548)
- [ ] change the map filters colour and font
- [ ] change [the design of the map markers](https://www.figma.com/file/dUL9ybnag2LhQpicJseFaH/Seismic-Risk?node-id=2066%3A4)
  - [ ] RS markers to #EE4036;
  - [ ] U markers to #EE741B;
  - [ ] N/A markers to the text `ALT` and #FF6984.
- [ ] change statistics icons for `people under risk` and `evaluated buildings`
- [ ] change statistics font properties
- [ ] change the `about project` and `blog` headings
- [ ] change the blog posts previews to use rounded corners

## [Blog](https://www.figma.com/file/dUL9ybnag2LhQpicJseFaH/Seismic-Risk?node-id=2066%3A2967)

- [ ] change the blog post design
  - [ ] change the order of the fields
  - [ ] change the font properties
- [ ] change the `load more articles` button

## [Blog post](https://www.figma.com/file/dUL9ybnag2LhQpicJseFaH/Seismic-Risk?node-id=2066%3A3379)

- [ ] change the buttons design font
- [ ] add `whatsapp` and `copy to clipboard` sharing
- [ ] change the sharing icons order to `copy to clipboard`, `facebook`, `twitter`, `whatsapp`, `telegram`

**Comment by vladplesu** [comment]
Hello! I can work on this one.
