### ISSUE TITLE
[Django] Clean up the old unused API

### ISSUE THREAD

**Issue by iuliux** [code4romania/seismic-risc#72]
Also called the "legacy API". We're at that stage where we don't have to keep legacy.

Should be safe to just completely nuke the `seismic_site/api` folder and remove this one line https://github.com/code4romania/seismic-risc/blob/master/seismic_site/seismic_site/urls.py#L27

While at it, the `seismic_site/map_app/serializers.py` is a complete duplicate (unused) of `seismic_site/buildings/serializers.py` (left-over from #61, my bad). This one would actually give an error if it were to be used.

**Comment by tudoramariei** [comment]
Since the app was refactored quite a bit, it should be OK to do a little clean-up
Thanks for bringing this up!
