### ISSUE TITLE
Main Page Bugs

### ISSUE THREAD

**Issue by vladplesu** [code4romania/seismic-risc#738]
You can choose to tackle one of the issues or more, the choice is yours

## General

- [ ] Default language is Romanian, but the page is loaded in English and afterwards switches to Romania.

![bulina_rosie_main_page_language](https://user-images.githubusercontent.com/22684808/137389046-d85fd938-c150-40bb-ba09-fae20a4578c8.gif)

## Map

- [ ] #773
the text from the `N/A` markers is the easiest where you can spot the bug
moving the map around with the cursor placed between a bunch of markers will result in them being highlighted 

![bulina_rosie_main_page_marker_cursor](https://user-images.githubusercontent.com/22684808/137390729-05f8df9b-8692-48b5-a318-332b7cde0ea8.gif)

- [x] After selecting a marker and clicking a new category, the map does not zoom to fit all markers from the selected category. Zooming in/out without selecting a marker and switching to another category will zoom to fit.

![bulina_rosie_main_page_zooming](https://user-images.githubusercontent.com/22684808/137391765-542cee12-1c3a-490c-b082-baa7ceb1469d.gif)

- [ ] Zooming in/out on the map also scrolls the page. It should either zoom in/out on the map or scroll the page, but not both.

![bulina_rosie_main_page_scrolling](https://user-images.githubusercontent.com/22684808/137392914-2c4a7f7c-0f95-46a5-bc45-1acef336ae82.gif)

## Search

- [ ] Search results contain buildings from all categories, even if a specific category is selected. Search results should be based on the selected category.

![bulina_rosie_main_page_search](https://user-images.githubusercontent.com/22684808/137395039-eba7d77a-bd44-4389-a422-79c812864579.gif)

**Comment by tudoramariei** [comment]
Closing this issue as all the bugs have been moved to separate issues
Thank you, @vladplesu for highlighting them 🙇
