### ISSUE TITLE
Have hCaptcha use the site language

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#742]
The captcha check from the building form uses English, indifferent of the language set on the site

Following the [hCaptcha guidelines](https://docs.hcaptcha.com/languages), pass the current language code (i.e. ro/en/hu) to the [hCaptcha fragment](https://github.com/code4romania/seismic-risc/blob/develop/client/src/containers/add-building/FormFragment.js#L201)

**Comment by CatalinCsnMaster** [comment]
If this is open, I can take it 😀
