### ISSUE TITLE
Blog post share buttons link to current post

### ISSUE THREAD

**Issue by vladplesu** [code4romania/seismic-risc#743]
Currently the share buttons for any post hold the link to the home page of `Bulina Rosie` .

The share buttons should hold the link to the blog post the user is currently viewing.

**Comment by tuanthanh2067** [comment]
Hello there, are these the buttons you are talking about

![image](https://user-images.githubusercontent.com/51014333/138339668-701b4236-ca1c-41ab-bfa2-4cfd6ce6fb1d.png)

If so, I can try to solve this issue!

**Comment by tudoramariei** [comment]
That's new 😳 
Does running `git status` offer any relevant information?
Looking over StackOverflow to understand what's happening 😅
