### ISSUE TITLE
Add the `add information (about a building)` functionality

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#765]
For any existing building displayed on the map, we should be able to crowdsource additional info about that building.

The workflow for adding more info to a building should look the following way
1. The user clicks on the `add information` button
2. The user is redirected to the `add new building` form (pre-filled with all the data we have about that building [1])
3. The user changes existing information or adds new info to empty fields
4. On sending the form, the original building's `general_id` is added as the `parent_id` of the data [2]

[1] - the contact info for that building will not be exposed and must therefore not be added to the form
[2] - the `/buildings/public_create` endpoint will be used here as well (with the additional `parent_id`)

**Comment by CatalinCsnMaster** [comment]
Hello! I can take this one 🔧

**Comment by tudoramariei** [comment]
Make sure you use the latest version of the form. #794 should be merged soon

**Comment by vladplesu** [comment]
Hello! I can take this one if @CatalinCsnMaster has not started working on it.

**Comment by CatalinCsnMaster** [comment]
@vladplesu I've almost finished this one 😄

**Comment by tudoramariei** [comment]
I am closing this task since it is outside the scope of the app at this time.
