### ISSUE TITLE
The app should not change languages in front of the user

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#772]
When the default language is Romanian or when the website first opens up it opens with the content in English first and then switches to Romanian

The expected behaviour is that if the website will open up directly with the language that is going to be used

![137389046-d85fd938-c150-40bb-ba09-fae20a4578c8](https://user-images.githubusercontent.com/2820084/144417603-fc2e08ad-8fab-47a1-8822-ca379c2ef84b.gif)

**Comment by CatalinCsnMaster** [comment]
I can take this one ✋
