### ISSUE TITLE
Zooming in/out on the map also scrolls the page

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#774]
It should either zoom in/out on the map or scroll the page, but not both
This behaviour generally happens when scrolling the page faster, on a computer

![137392914-2c4a7f7c-0f95-46a5-bc45-1acef336ae82](https://user-images.githubusercontent.com/2820084/144421169-9d0db661-77d4-4a77-ae5f-aa0712e91e65.gif)

**Comment by CatalinCsnMaster** [comment]
Hey! I'll take this one
