### ISSUE TITLE
Filter search results by selected category

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#775]
Search results contain buildings from all categories, even if a specific category is selected. Search results should be based on the selected category

- [ ] **back-end:** update the search endpoint to filter results based on a `searchCategory` parameter (shouldn't be mandatory)
- [ ] **front-end:** pass the selected map filter from the filters bar to the search endpoint

<img width="987" alt="Screenshot 2021-12-02 at 15 12 40" src="https://user-images.githubusercontent.com/2820084/144428703-c267219e-4367-4686-8f9f-d9afff332976.png">

example endpoint:
```
/search/?query=victoriei&riskCategory=N/A
```

**Comment by CatalinCsnMaster** [comment]
I choose this Pokemon, already done the BE part, going forward with FE
