### ISSUE TITLE
[front-end] Create an embeddable page that contains the map elements

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#884]
Create a single page that contains the elements presented in the screenshot.
The page will later be embedded as an iframe and should allow interaction with all elements.
- [ ] the search bar
- [ ] the map with buildings
- [ ] the statistics

![Screenshot 2023-03-31 at 22 08 38 copy](https://user-images.githubusercontent.com/2820084/229217931-c4806939-9a14-4b21-b203-55a16afa2bc9.png)

**Comment by alinaMihai** [comment]
@tudoramariei I will take this one!
