### ISSUE TITLE
[front-end] Remove all the unused elements from the site 

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#886]
Only the main and the `add-building` pages will be necessary for the app. 
All other pages should be removed.

**Comment by danmic94** [comment]
salut @tudoramariei  e ok daca il iau eu ? (fac setupul local si dupa ma ocup de el ASAP) (FYI prima activitate pentru code4romania 🤯 😄 )

**Comment by tudoramariei** [comment]
Sună bine, @danmic94!
Dacă mai sunt întrebări, mă găsești pe aici și pe slack-ul code4 😄
