### ISSUE TITLE
[back-end] Fix the `original building` selector in admin

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#891]
The selector in the admin is too large for most web screens due to the size of the `building.__str__()`.
The selector should fit inside the body of its card and not bleed, overlapping with other components.

![image](https://user-images.githubusercontent.com/2820084/229275429-a4125d18-0322-4db8-9718-e7970bf19f32.png)

**Comment by calindragomir** [comment]
@tudoramariei looking on this one.

**Comment by tudoramariei** [comment]
The issue was fixed by #901, but the build didn't run properly because of a configuration issue. 
Thanks, @calindragomir, for solving it; the fix is up now.
