### ISSUE TITLE
[front-end] Update client requirements

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#899]
Update the requirements for the client.
The app should be compatible with `Node 18` (or at least `Node 16`).
Make sure also to cover the Dockerfile.

**Comment by alinaMihai** [comment]
hi, @tudoramariei I will take this one.

**Comment by tudoramariei** [comment]
Thanks for the help, @alinaMihai! I merged your PR. 
We'll look over updating the rest of the dependencies, though routing shouldn't be  that important anymore.
Great work! 🚀
