### ISSUE TITLE
[front-end] Selecting a search result prints the ID instead of the address

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#912]
When selecting a building from the search drop-down, the result that appears in the search bar is the ID of the building instead of the address that was clicked on.

Relates to #911 

https://github.com/code4romania/seismic-risc/assets/2820084/e9451ff0-8b72-4a20-bda5-93e43f3590e4

**Comment by alinaMihai** [comment]
@tudoramariei I will work on this one!
