### ISSUE TITLE
[client] Make use of the API to get map data

### ISSUE THREAD

**Issue by aramboi** [code4romania/seismic-risc#92]
Right now the client uses an outdated json dump of the data and the `json-server` package to serve it.

The client code should be able to take an environment variable with the site domain and get the data directly from the api. 

You can load some dummy data into the `buildings` api by running the `make init-db` (this will also create a superuser for you in the django admin).

**Comment by tudoramariei** [comment]
The API is currently able to send data, which just needs to be fetched
The endpoint can be found at `/api/v1/*` 
Where `*` can be either `buildings`, `pages` or `posts`

**Comment by emanuelbesliu** [comment]
Taking this one.

**Comment by vladplesu** [comment]
Hello! I can work on this one.
