### ISSUE TITLE
[frontend] Create detailed building view

### ISSUE THREAD

**Issue by catileptic** [code4romania/seismic-risc#95]
As a user, when I click on a building, I want to see a side-view on the right-hand side of the map where I can read all the details about the currently selected building, in order to understand the context in which it was marked as being a risk. 

As reference, use [the second mockup image](https://www.figma.com/file/qOyFrU8T6LXnJw7YcoVW85/Seismic-Risk?node-id=0%3A1).

**Comment by vladplesu** [comment]
Hello, I can take this one.
