### ISSUE TITLE
Internationalise the interface

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc#97]
All the text displayed should be multilingual, allowing us to deploy the application in different languages
This also allows the display of Romanian strings while at the same time allowing developers to easily understand what those strings represent

Languages supported: en-GB (code language), ro-RO

Mock text can be used in the beginning to not spend much time on translating everything

Relevant React i18n docs:

- https://github.com/i18next/react-i18next 
- https://www.freecodecamp.org/news/setting-up-internationalization-in-react-from-start-to-finish-6cb94a7af725

**Comment by AlexandruBuhai** [comment]
I'll take this again for this hackday!
